global:
  sendAnonymousUsage: false

api:
  dashboard: true

# Inside docker network, skip verify ssl
serversTransport:
  insecureSkipVerify: true

providers:
  file:
    directory: /etc/traefik/conf.d
    watch: true
  docker:
    endpoint: unix:///var/run/docker.sock
    watch: true
    exposedByDefault: false

log:
  level: INFO
  format: common

# predefined entry points for each port
entryPoints:
  # 11300-11309
  port-11300:
    address: ":11300"
  port-11301:
    address: ":11301"
  port-11302:
    address: ":11302"
  port-11303:
    address: ":11303"
  port-11304:
    address: ":11304"
  port-11305:
    address: ":11305"
  port-11306:
    address: ":11306"
  port-11307:
    address: ":11307"
  port-11308:
    address: ":11308"
  port-11309:
    address: ":11309"
  # 11443
  port-11443:
    address: ":11443"
